/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure

    // docsSidebar: [{type: 'autogenerated', dirName: '.'}],

    docsSidebar: [
        {
            type: 'html',
            value: '<div class="wwads-cn wwads-horizontal" data-id="235" style="max-width:350px"></div>', // 要渲染的 HTML
            defaultStyle: true, // 使用默认的菜单项目样式
        },
        'intro',
        {
            type: 'category',
            label: '快速安装（必看）',
            // collapsed: false,
            link: {
                type: 'generated-index',
                title: '快速安装',
                description: '请选择安装方式',
                slug: '/install'
            },
            items: [
                {
                    id: 'install/guide',
                    type: 'doc',
                    label: '安装向导（推荐）'
                },
                {
                    type: 'doc',
                    label: '帮我安装',
                    id: 'support/support'
                }
            ],
        },
        {
            type: 'category',
            label: '功能介绍',
            items: [
                {
                    id: 'feature/pwd-folder',
                    type: 'doc',
                    label: '文件夹密码/加密'
                },
                {
                    id: 'feature/md-folder',
                    type: 'doc',
                    label: '文件夹文档'
                },
                {
                    id: 'feature/hidden-file',
                    type: 'doc',
                    label: '隐藏文件/文件夹'
                },
                {
                    id: 'feature/video',
                    type: 'doc',
                    label: '视频播放'
                },
                {
                    id: 'feature/text',
                    type: 'doc',
                    label: '文本预览'
                },
                {
                    id: 'feature/music',
                    type: 'doc',
                    label: '音频播放'
                },
                {
                    id: 'feature/pdf',
                    type: 'doc',
                    label: 'PDF 预览'
                },
                {
                    id: 'feature/office',
                    type: 'doc',
                    label: 'office 预览'
                },
                {
                    id: 'feature/log',
                    type: 'doc',
                    label: '系统日志'
                },
                {
                    id: 'feature/system-monitor',
                    type: 'doc',
                    label: '系统监控'
                }
            ]
        },
        {
            type: 'category',
            label: '配置文件',
            items: [
                {
                    id: 'config/config-path',
                    type: 'doc',
                    label: '配置文件路径（必看）'
                },
                {
                    id: 'config/config-port',
                    type: 'doc',
                    label: '启动端口'
                },
                {
                    id: 'config/config-db',
                    type: 'doc',
                    label: '数据库配置'
                },
                {
                    id: 'config/config-debug',
                    type: 'doc',
                    label: 'Debug 模式'
                }
            ]
        },
        {
            type: 'category',
            label: '高级功能',
            items: [
                {
                    id: 'advanced/cf-worker',
                    type: 'doc',
                    label: 'OneDrive CF Worker 加速'
                },
                {
                    id: 'advanced/google-drive-api',
                    type: 'doc',
                    label: '自建 Google Drive API'
                },
                {
                    id: 'advanced/onedrive-api',
                    type: 'doc',
                    label: '自建 OneDrive API'
                },
                {
                    id: 'advanced/only-office',
                    type: 'doc',
                    label: '自建 OnlyOffice'
                }
            ]
        },
        {
            type: 'category',
            label: '常见问题',
            items: [
                {
                    id: 'question/systemd-config',
                    type: 'doc',
                    label: '如何配置开机自启(systemd)？'
                },
                {
                    id: 'question/backup',
                    type: 'doc',
                    label: '如何备份/迁移程序数据？'
                },
                {
                    id: 'question/bind-domain',
                    type: 'doc',
                    label: '如何用域名访问？'
                },
                {
                    id: 'question/start-fail',
                    type: 'doc',
                    label: '启动失败/无法访问怎么办？'
                },
                {
                    id: 'question/update-config-file',
                    type: 'doc',
                    label: '如何修改配置文件？'
                },
                {
                    id: 'question/run-multiple-instance',
                    type: 'doc',
                    label: '如何运行多个 ZFile 实例？'
                },
                {
                    id: 'question/nginx-1g-download-fail',
                    type: 'doc',
                    label: '使用 Nginx 反向代理后，下载 1G 以上文件失败?'
                },
                {
                    id: 'question/nginx-proxy-config',
                    type: 'doc',
                    label: '为什么我启用了 https，但直链下载会被重定向到 http?'
                },
                {
                    id: 'question/nginx-proxy-config',
                    type: 'doc',
                    label: '为什么我通过域名访问的项目，但重定向到了项目内网地址？'
                },
                {
                    id: 'question/nginx-proxy-config',
                    type: 'doc',
                    label: '为什么我启用了 https，但直链下载浏览器提示"此网站使用的不是安全链接，该文件可能已被篡改"'
                },
                {
                    id: 'question/only-office-download-fail',
                    type: 'doc',
                    label: 'OnlyOffice 预览失败怎么办？'
                },
                {
                    id: 'question/ubuntu-awt',
                    type: 'doc',
                    label: 'Ubuntu 登录页报错'
                },
                {
                    id: 'question/reset-password',
                    type: 'doc',
                    label: '忘记管理员密码怎么办？'
                },
                {
                    id: 'question/forget-secure-login-entry',
                    type: 'doc',
                    label: '忘记登录安全入口怎么办？'
                },
                {
                    id: 'question/cat-current-version',
                    type: 'doc',
                    label: '查看 ZFile 版本'
                },
                {
                    id: 'question/upload-fail',
                    type: 'doc',
                    label: '上传失败怎么办？'
                },
                {
                    id: 'question/garbled',
                    type: 'doc',
                    label: '文件名乱码如何处理？'
                },
                {
                    id: 'question/separation-of-front-end-and-backend',
                    type: 'doc',
                    label: '如何前后端分离部署？'
                },
                {
                    id: 'question/download-log',
                    type: 'doc',
                    label: '如何查看/下载日志？'
                },
                {
                    id: 'question/modify-favicon',
                    type: 'doc',
                    label: '如何修改左上角 favicon 图标？'
                },
                {
                    id: 'question/cf-not-work',
                    type: 'doc',
                    label: '为什么我使用 Cloudflare 后页面白屏无法访问？'
                },
                {
                    id: 'question/remove-copyright',
                    type: 'doc',
                    label: '如何去除版权信息？'
                }
            ]
        },
        {
            type: 'doc',
            label: '存储源类型对比',
            id: 'storage-type'
        },
        {
            type: 'category',
            label: '存储源示例配置🔥',
            link: {
                description: "如果你不知道怎么配置存储源，可以点击下方你想添加的存储类型查看详细文档",
                type: 'generated-index',
            },
            items: [
                {
                    id: 'example/oss',
                    type: 'doc',
                    label: '阿里云 OSS'
                },
                {
                    id: 'example/cos',
                    type: 'doc',
                    label: '腾讯云 COS'
                },
                {
                    id: 'example/obs',
                    type: 'doc',
                    label: '华为云 OBS'
                },
                {
                    id: 'example/upyun',
                    type: 'doc',
                    label: '又拍云'
                },
                {
                    id: 'example/qiniu',
                    type: 'doc',
                    label: '七牛云'
                },
                {
                    id: 'example/minio',
                    type: 'doc',
                    label: 'MINIO'
                },
                {
                    id: 'example/rains3',
                    type: 'doc',
                    label: 'Rain S3 雨云存储'
                },
                {
                    id: 'example/digitalocean',
                    type: 'doc',
                    label: 'DigitalOcean Spaces'
                },
                {
                    id: 'example/r2',
                    type: 'doc',
                    label: 'Cloudflare R2'
                },
                {
                    id: 'example/oracle',
                    type: 'doc',
                    label: 'Oracle 对象存储'
                },
                {
                    id: 'example/b2',
                    type: 'doc',
                    label: 'Backblaze（b2）'
                },
                {
                    id: 'example/s3',
                    type: 'doc',
                    label: 'S3 或其他兼容 S3 的服务'
                },
                {
                    id: 'example/onedrive',
                    type: 'doc',
                    label: 'OneDrive'
                },
                {
                    id: 'example/onedrive-china',
                    type: 'doc',
                    label: 'OneDrive (世纪互联)'
                },
                {
                    id: 'example/sharepoint',
                    type: 'doc',
                    label: 'SharePoint'
                },
                {
                    id: 'example/sharepoint-china',
                    type: 'doc',
                    label: 'SharePoint (世纪互联)'
                },
                {
                    id: 'example/ftp',
                    type: 'doc',
                    label: 'FTP'
                },
                {
                    id: 'example/sftp',
                    type: 'doc',
                    label: 'SFTP'
                },
            ]
        },
        {
            type: 'category',
            label: '自定义 JS 示例',
            link: {
                type: 'generated-index',
                title: '自定义 JS 相关示例',
                description: '点击下方查看不同版本的更新日志',
                slug: '/custom-js'
            },
            items: [
                {
                    id: 'custom-js/51la',
                    type: 'doc',
                    label: '51LA 统计'
                },
                {
                    id: 'custom-js/baidu-tongji',
                    type: 'doc',
                    label: '百度统计'
                }
            ]
        },
        {
            type: 'category',
            label: '更新日志',
            link: {
                type: 'generated-index',
                title: '更新日志',
                description: '点击下方查看不同版本的更新日志',
                slug: '/changelog'
            },
            items: [
                {
                    id: 'changelog/os',
                    type: 'doc',
                    label: '开源版'
                },
                {
                    id: 'changelog/pro',
                    type: 'doc',
                    label: '捐赠版'
                }
            ]
        },
        {
            type: 'doc',
            label: '服务器推荐✨',
            id: 'ad/ad'
        },
        {
            type: 'doc',
            label: '技术支持',
            id: 'support/support'
        }
    ],

};

module.exports = sidebars;